name: MLOps Pipeline with DVC & Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install DVC and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc
          pip install torch torchvision

      - name: Initialize DVC
        run: |
          dvc init  # Initializes DVC if not already done

      - name: Download Fashion MNIST data
        run: |
          python -c "
          import torchvision
          import torch
          transform = torchvision.transforms.Compose([torchvision.transforms.ToTensor()])
          torchvision.datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
          "
          
      - name: Track Fashion MNIST data with DVC
        run: |
          dvc add data  # Tracks the downloaded data with DVC
          git add data.dvc .gitignore
          git commit -m "Track Fashion MNIST data with DVC"

      - name: Run EDA and generate report
        run: |
          python src/eda.py
          
      - name: Upload EDA report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: eda-report
          path: eda_report.html

  docker:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fashion-mnist-mlops:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fashion-mnist-mlops:latest
